
timezone: America/Argentina/Buenos_Aires
telegram.enabled: false
telegram.bot_token: ""
telegram.chat_id: ""
email.enabled: false
email.smtp_host: smtp.example.com
email.smtp_port: 587
email.username: ""
email.password: ""
email.to: you@example.com
